[2024-09-24T11:34:34.602+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-24T11:34:34.640+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_dag.dbt_test manual__2024-09-24T11:32:30.300237+00:00 [queued]>
[2024-09-24T11:34:34.658+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_dag.dbt_test manual__2024-09-24T11:32:30.300237+00:00 [queued]>
[2024-09-24T11:34:34.658+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-09-24T11:34:34.684+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): dbt_test> on 2024-09-24 11:32:30.300237+00:00
[2024-09-24T11:34:34.697+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=808) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-24T11:34:34.699+0000] {standard_task_runner.py:72} INFO - Started process 809 to run task
[2024-09-24T11:34:34.697+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dbt_dag', 'dbt_test', 'manual__2024-09-24T11:32:30.300237+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/dbt_snowflake_dag.py', '--cfg-path', '/tmp/tmpnnvb6nml']
[2024-09-24T11:34:34.701+0000] {standard_task_runner.py:105} INFO - Job 40: Subtask dbt_test
[2024-09-24T11:34:34.725+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-09-24T11:34:34.787+0000] {task_command.py:467} INFO - Running <TaskInstance: dbt_dag.dbt_test manual__2024-09-24T11:32:30.300237+00:00 [running]> on host cb04601716d3
[2024-09-24T11:34:34.965+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Amir' AIRFLOW_CTX_DAG_ID='dbt_dag' AIRFLOW_CTX_TASK_ID='dbt_test' AIRFLOW_CTX_EXECUTION_DATE='2024-09-24T11:32:30.300237+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-24T11:32:30.300237+00:00'
[2024-09-24T11:34:34.966+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-24T11:34:35.004+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-24T11:34:35.006+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/code/sales_dbt && dbt test']
[2024-09-24T11:34:35.024+0000] {subprocess.py:86} INFO - Output:
[2024-09-24T11:34:39.743+0000] {subprocess.py:93} INFO - [0m11:34:39  Running with dbt=1.8.6
[2024-09-24T11:34:41.737+0000] {subprocess.py:93} INFO - [0m11:34:41  Registered adapter: snowflake=1.8.3
[2024-09-24T11:34:42.649+0000] {subprocess.py:93} INFO - [0m11:34:42  Found 10 models, 1 seed, 1 operation, 12 data tests, 1 source, 656 macros
[2024-09-24T11:34:42.657+0000] {subprocess.py:93} INFO - [0m11:34:42
[2024-09-24T11:34:45.511+0000] {subprocess.py:93} INFO - [0m11:34:45  Concurrency: 1 threads (target='dev')
[2024-09-24T11:34:45.512+0000] {subprocess.py:93} INFO - [0m11:34:45
[2024-09-24T11:34:45.531+0000] {subprocess.py:93} INFO - [0m11:34:45  1 of 12 START test not_null_dim_customer_CUSTOMER_ID ........................... [RUN]
[2024-09-24T11:34:46.651+0000] {subprocess.py:93} INFO - [0m11:34:46  1 of 12 PASS not_null_dim_customer_CUSTOMER_ID ................................. [[32mPASS[0m in 1.12s]
[2024-09-24T11:34:46.656+0000] {subprocess.py:93} INFO - [0m11:34:46  2 of 12 START test not_null_dim_date_ORDER_DATE ................................ [RUN]
[2024-09-24T11:34:47.676+0000] {subprocess.py:93} INFO - [0m11:34:47  2 of 12 PASS not_null_dim_date_ORDER_DATE ...................................... [[32mPASS[0m in 1.02s]
[2024-09-24T11:34:47.682+0000] {subprocess.py:93} INFO - [0m11:34:47  3 of 12 START test not_null_dim_location_LOCATION_ID ........................... [RUN]
[2024-09-24T11:34:48.870+0000] {subprocess.py:93} INFO - [0m11:34:48  3 of 12 PASS not_null_dim_location_LOCATION_ID ................................. [[32mPASS[0m in 1.18s]
[2024-09-24T11:34:48.876+0000] {subprocess.py:93} INFO - [0m11:34:48  4 of 12 START test not_null_dim_product_PRODUCT_ID ............................. [RUN]
[2024-09-24T11:34:49.711+0000] {subprocess.py:93} INFO - [0m11:34:49  4 of 12 PASS not_null_dim_product_PRODUCT_ID ................................... [[32mPASS[0m in 0.83s]
[2024-09-24T11:34:49.716+0000] {subprocess.py:93} INFO - [0m11:34:49  5 of 12 START test relationships_fact_CUSTOMER_ID__CUSTOMER_ID__ref_dim_customer_  [RUN]
[2024-09-24T11:34:50.720+0000] {subprocess.py:93} INFO - [0m11:34:50  5 of 12 PASS relationships_fact_CUSTOMER_ID__CUSTOMER_ID__ref_dim_customer_ .... [[32mPASS[0m in 1.00s]
[2024-09-24T11:34:50.728+0000] {subprocess.py:93} INFO - [0m11:34:50  6 of 12 START test relationships_fact_LOCATION_ID__LOCATION_ID__ref_dim_location_  [RUN]
[2024-09-24T11:34:53.089+0000] {subprocess.py:93} INFO - [0m11:34:53  6 of 12 PASS relationships_fact_LOCATION_ID__LOCATION_ID__ref_dim_location_ .... [[32mPASS[0m in 2.36s]
[2024-09-24T11:34:53.094+0000] {subprocess.py:93} INFO - [0m11:34:53  7 of 12 START test relationships_fact_ORDER_DATE__ORDER_DATE__ref_dim_date_ .... [RUN]
[2024-09-24T11:34:54.380+0000] {subprocess.py:93} INFO - [0m11:34:54  7 of 12 ERROR relationships_fact_ORDER_DATE__ORDER_DATE__ref_dim_date_ ......... [[31mERROR[0m in 1.28s]
[2024-09-24T11:34:54.385+0000] {subprocess.py:93} INFO - [0m11:34:54  8 of 12 START test relationships_fact_PRODUCT_ID__PRODUCT_ID__ref_dim_product_ . [RUN]
[2024-09-24T11:34:55.877+0000] {subprocess.py:93} INFO - [0m11:34:55  8 of 12 PASS relationships_fact_PRODUCT_ID__PRODUCT_ID__ref_dim_product_ ....... [[32mPASS[0m in 1.49s]
[2024-09-24T11:34:55.880+0000] {subprocess.py:93} INFO - [0m11:34:55  9 of 12 START test unique_dim_customer_CUSTOMER_ID ............................. [RUN]
[2024-09-24T11:34:56.777+0000] {subprocess.py:93} INFO - [0m11:34:56  9 of 12 PASS unique_dim_customer_CUSTOMER_ID ................................... [[32mPASS[0m in 0.89s]
[2024-09-24T11:34:56.780+0000] {subprocess.py:93} INFO - [0m11:34:56  10 of 12 START test unique_dim_date_ORDER_DATE ................................. [RUN]
[2024-09-24T11:34:57.489+0000] {subprocess.py:93} INFO - [0m11:34:57  10 of 12 PASS unique_dim_date_ORDER_DATE ....................................... [[32mPASS[0m in 0.71s]
[2024-09-24T11:34:57.493+0000] {subprocess.py:93} INFO - [0m11:34:57  11 of 12 START test unique_dim_location_LOCATION_ID ............................ [RUN]
[2024-09-24T11:34:58.402+0000] {subprocess.py:93} INFO - [0m11:34:58  11 of 12 PASS unique_dim_location_LOCATION_ID .................................. [[32mPASS[0m in 0.91s]
[2024-09-24T11:34:58.407+0000] {subprocess.py:93} INFO - [0m11:34:58  12 of 12 START test unique_dim_product_PRODUCT_ID .............................. [RUN]
[2024-09-24T11:34:59.257+0000] {subprocess.py:93} INFO - [0m11:34:59  12 of 12 PASS unique_dim_product_PRODUCT_ID .................................... [[32mPASS[0m in 0.85s]
[2024-09-24T11:34:59.261+0000] {subprocess.py:93} INFO - [0m11:34:59
[2024-09-24T11:34:59.262+0000] {subprocess.py:93} INFO - [0m11:34:59  Running 1 on-run-end hook
[2024-09-24T11:34:59.293+0000] {subprocess.py:93} INFO - [0m11:34:59  1 of 1 START hook: dbt_constraints.on-run-end.0 ................................ [RUN]
[2024-09-24T11:34:59.294+0000] {subprocess.py:93} INFO - [0m11:34:59  1 of 1 OK hook: dbt_constraints.on-run-end.0 ................................... [[32mOK[0m in 0.00s]
[2024-09-24T11:34:59.295+0000] {subprocess.py:93} INFO - [0m11:34:59
[2024-09-24T11:34:59.298+0000] {subprocess.py:93} INFO - [0m11:34:59
[2024-09-24T11:34:59.299+0000] {subprocess.py:93} INFO - [0m11:34:59  Finished running 12 data tests, 1 project hook in 0 hours 0 minutes and 16.64 seconds (16.64s).
[2024-09-24T11:34:59.517+0000] {subprocess.py:93} INFO - [0m11:34:59
[2024-09-24T11:34:59.518+0000] {subprocess.py:93} INFO - [0m11:34:59  [31mCompleted with 1 error and 0 warnings:[0m
[2024-09-24T11:34:59.519+0000] {subprocess.py:93} INFO - [0m11:34:59
[2024-09-24T11:34:59.520+0000] {subprocess.py:93} INFO - [0m11:34:59    Database Error in test relationships_fact_ORDER_DATE__ORDER_DATE__ref_dim_date_ (models/marts/schema.yml)
[2024-09-24T11:34:59.520+0000] {subprocess.py:93} INFO -   100040 (22007): Date '15/04/2017' is not recognized
[2024-09-24T11:34:59.521+0000] {subprocess.py:93} INFO -   compiled Code at target/run/sales_dbt/models/marts/schema.yml/relationships_fact_ORDER_DATE__ORDER_DATE__ref_dim_date_.sql
[2024-09-24T11:34:59.521+0000] {subprocess.py:93} INFO - [0m11:34:59
[2024-09-24T11:34:59.522+0000] {subprocess.py:93} INFO - [0m11:34:59  Done. PASS=11 WARN=0 ERROR=1 SKIP=0 TOTAL=12
[2024-09-24T11:35:01.078+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-09-24T11:35:01.095+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-09-24T11:35:01.103+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=dbt_dag, task_id=dbt_test, run_id=manual__2024-09-24T11:32:30.300237+00:00, execution_date=20240924T113230, start_date=20240924T113434, end_date=20240924T113501
[2024-09-24T11:35:01.132+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-24T11:35:01.133+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 40 for task dbt_test (Bash command failed. The command returned a non-zero exit code 1.; 809)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-09-24T11:35:01.182+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-09-24T11:35:01.214+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-24T11:35:01.216+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
